default: &default
  dispatchers:
    - polling_interval: <%= ENV.fetch("SOLID_QUEUE_POLLING_INTERVAL", 1) %>
      batch_size: 500
  workers:
    - queues: "*"
      threads: <%= ENV.fetch("SOLID_QUEUE_THREADS", 5) %>
      processes: <%= ENV.fetch("SOLID_QUEUE_WORKERS", 1) %>
      polling_interval: <%= ENV.fetch("SOLID_QUEUE_POLLING_INTERVAL", 1) %>
  supervisor:
    - kind: supervisor
      threads: 1


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
