name: Release

on:
  push:
    branches:
      - main # mainブランチにマージされたら実行

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install standard-version
        run: npm install -g standard-version

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Run standard-version
        run: |
          # VERSION ファイルと CHANGELOG.md を自動更新し、Gitタグを生成
          standard-version --infile CHANGELOG.md

      - name: Push changes and tags
        run: |
          git push origin main --follow-tags
